name: Run UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ui-test-ios:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Resolve and update Swift packages  
        run: xcodebuild -resolvePackageDependencies -scheme Authenticator

      - name: UI test Authenticator on iOS
        working-directory: Tests/AuthenticatorHostApp
        run: |
          xcodebuild -resolvePackageDependencies -scheme Authenticator
          xcodebuild test -scheme AuthenticatorHostApp -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' -derivedDataPath Build/ -clonedSourcePackagesDirPath ~/Library/Developer/Xcode/DerivedData/Authenticator | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]}
